// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6315LoDmILFnmXGLqEovXuMd_J2I2-tc',
    appId: '1:113955999228:web:088004d10886871e1bb679',
    messagingSenderId: '113955999228',
    projectId: 'todoappriverpod',
    authDomain: 'todoappriverpod.firebaseapp.com',
    storageBucket: 'todoappriverpod.firebasestorage.app',
    measurementId: 'G-KQJMSNMG9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBPqZJwnW7XuH86hUhhdg9GGOYe5V2nKc',
    appId: '1:113955999228:android:123c09d6e27cda6c1bb679',
    messagingSenderId: '113955999228',
    projectId: 'todoappriverpod',
    storageBucket: 'todoappriverpod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRf91k9qA5VB_0jxEPdMiucWf0e86mpGg',
    appId: '1:113955999228:ios:f29e0748cebf63191bb679',
    messagingSenderId: '113955999228',
    projectId: 'todoappriverpod',
    storageBucket: 'todoappriverpod.firebasestorage.app',
    iosBundleId: 'com.example.switchAppRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRf91k9qA5VB_0jxEPdMiucWf0e86mpGg',
    appId: '1:113955999228:ios:f29e0748cebf63191bb679',
    messagingSenderId: '113955999228',
    projectId: 'todoappriverpod',
    storageBucket: 'todoappriverpod.firebasestorage.app',
    iosBundleId: 'com.example.switchAppRiverpod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhJADQGDBE_rAnQt-Y2X3J-lIhjcGq3UU',
    appId: '1:113955999228:web:c6dcc0e44d5dc2681bb679',
    messagingSenderId: '113955999228',
    projectId: 'todoappriverpod',
    authDomain: 'todoappriverpod.firebaseapp.com',
    storageBucket: 'todoappriverpod.firebasestorage.app',
    measurementId: 'G-HNRZ3E9GZ4',
  );
}
