// Mocks generated by Mockito 5.4.6 from annotations
// in switch_app_riverpod/test/utils/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:switch_app_riverpod/data/dto/switch_dto.dart' as _i3;
import 'package:switch_app_riverpod/data/repository/switch_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRef_0<State extends Object?> extends _i1.SmartFake
    implements _i2.Ref<State> {
  _FakeRef_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSwitchDto_1 extends _i1.SmartFake implements _i3.SwitchDto {
  _FakeSwitchDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SwitchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSwitchRepository extends _i1.Mock implements _i4.SwitchRepository {
  MockSwitchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ref<Object?> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeRef_0<Object?>(this, Invocation.getter(#ref)),
          )
          as _i2.Ref<Object?>);

  @override
  _i5.Future<_i3.SwitchDto> getSwitchIsEnabled({required String? documentId}) =>
      (super.noSuchMethod(
            Invocation.method(#getSwitchIsEnabled, [], {
              #documentId: documentId,
            }),
            returnValue: _i5.Future<_i3.SwitchDto>.value(
              _FakeSwitchDto_1(
                this,
                Invocation.method(#getSwitchIsEnabled, [], {
                  #documentId: documentId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.SwitchDto>);

  @override
  _i5.Future<void> switchOn({required String? documentId}) =>
      (super.noSuchMethod(
            Invocation.method(#switchOn, [], {#documentId: documentId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> switchOff({required String? documentId}) =>
      (super.noSuchMethod(
            Invocation.method(#switchOff, [], {#documentId: documentId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
